#NAME THE PIPELINE SAME AS FILE (WITHOUT ".yml")

resources:
  repositories:
    - repository: self
      trigger: none

variables:
  - group: lab-vars            # azureServiceConnection + resourceGroup + location + subscriptionId (detected at startup)

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      name: kk-devops-agent-pool
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Deploy App Service using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/webapp-docker.bicep'
        deploymentMode: 'Incremental'
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: Add Role Assignment using Bicep
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(azureServiceConnection)
        subscriptionId: $(subscriptionId)
        action: 'Create Or Update Resource Group'
        resourceGroupName: '$(resourceGroup)'
        location: '$(location)'
        templateLocation: 'Linked artifact'
        csmFile: 'infra/webapp-to-acr-roleassignment.bicep'
        deploymentMode: 'Incremental'
